### ISSUE TITLE
Encountering an error with a multi-echo data set

### ISSUE THREAD

**Issue by emmabiondetti** [korbinian90/ROMEO#10]
Dear Korbinian,

I am encountering an issue with running ROMEO on a multi-echo data set, as it throws the error:
"ERROR: AssertionError: Unwrap-weights are all zero!"

If I run ROMEO on individual echoes from this data set, it works fine, so this issue is limited to the multi-echo combination procedure. 
I tested ROMEO on this data set using both the MRITools and Neurodesk implementations, obtaining the same error.  
As a further test, I successfully ran ROMEO on a different multi-echo data set (in Neurodesk). Thus, this is not an installation issue but something specific to this one data set.

I would appreciate your input on this! 

Thanks,
Emma

**Comment by korbinian90** [comment]
Dear Emma,

Thank you for reporting this error and for doing the tests! Can you share this dataset for debugging?

The only reason I can think of would be a Nifti read problem. Sometimes nifti headers have weird settings, like a scaling factor of 0. I tried to catch these, but maybe something I didn't encounter yet.

Btw: Did you use the -i (--individual-unwrapping) option on the 4d dataset when it crashed?

**Comment by emmabiondetti** [comment]
Hi Korbinian,

Thanks for your quick reply. 

I have shared the data set with your Gmail address via Google Drive.

To answer your question, I was not using the -i option on the 4D data set when it crashed. I tested again with the -i option, and I got the same error.

Thanks!

**Comment by korbinian90** [comment]
Hi Emma,

I located the issue in the automatic scaling of the phase input images.

A workaround at the moment is to manually scale the phase to the range [-π;π] for ROMEO as the phase input and set the option --no-rescale.

I'll fix it and release a new version
Thanks for reporting this ;)

**Comment by emmabiondetti** [comment]
Hi Korbinian, 

Thank you for your help! 
I will apply this workaround until the next version is released.
