### ISSUE TITLE
Problem with coil combination using the romeo binary

### ISSUE THREAD

**Issue by mavel101** [korbinian90/ROMEO#12]
Thanks for this nice unwrapping tool.

I have a problem when I run the romeo binary with 5D magnitude and phase data (2-echo scans). The coil combination seems to be not working correctly as the combined magnitude images lose all contrast and are very noisy.

If I do a 2 step unwrapping, running the mcpc3ds binary first, the coil combined images look fine.
These are my command line inputs:
1 step: 
bin/romeo -p phs.nii.gz -m mag.nii.gz --no-rescale -B -t [2.42,4.84] -o .
2 step:
bin/mcpc3ds -m mag.nii.gz -p phs.nii.gz -t [2.42,4.84] --no-phase-rescale -o .
bin/romeo -p combined_phase.nii -m combined_mag.nii --no-rescale -B -t [2.42,4.84] -o .

mag.nii.gz and phs.nii.gz are both 5D images [x,y,z,echo,coil].

I am using the standalone executables.

**Comment by korbinian90** [comment]
Thanks for reporting this!
I will try to reproduce it

**Comment by korbinian90** [comment]
The problem should be solved in the newest release.
The problem was that the combination didn't use the magnitude at all and the written combined magnitude was similar to a "combination quality map".
Thanks again for finding and reporting this!
