### ISSUE TITLE
Does not support phase difference input?

### ISSUE THREAD

**Issue by xingwangyong** [korbinian90/ROMEO#15]
Thanks for this handy tool.

If I use `-p phase_diff.nii` (only 2D matrix inside), it would complain. Although at the beginning the doc says need 4D nifti, later the doc says we can input phase difference data. Am I missing something here?
> This might be necessary for phase difference data,

error when trying to use phase difference data.
> ERROR: BoundsError: attempt to access Tuple{Int64, Int64} at index [3]
Stacktrace:
 [1] getindex
   @ .\tuple.jl:29 [inlined]
 [2] getindex(t::Tuple, r::UnitRange{Int64})
   @ Base .\range.jl:313
 [3] load_data_and_resolve_args!(settings::Dict{String, Any})
   @ RomeoApp C:\Users\runneradmin\.julia\packages\RomeoApp\xDyvE\src\caller.jl:78
 [4] unwrapping_main(args::Vector{String}; version::String)
   @ RomeoApp C:\Users\runneradmin\.julia\packages\RomeoApp\xDyvE\src\caller.jl:3
 [5] julia_main(version::String)
   @ RomeoApp C:\Users\runneradmin\.julia\packages\RomeoApp\xDyvE\src\RomeoApp.jl:12
 [6] romeo()
   @ App D:\a\CompileMRI.jl\CompileMRI.jl\App\src\App.jl:9
 [7] top-level scope
   @ none:1

**Comment by korbinian90** [comment]
Hi xingwangyong,
Thanks for reporting this! I could reproduce it.
It is a bug. I think the problem is the 2D input, I will try to find the problem and fix it.

**Comment by korbinian90** [comment]
fixed the bug and released a new version [3.6.6.](https://github.com/korbinian90/CompileMRI.jl/releases/tag/v3.6.6)
2D input data should now be supported
