### ISSUE TITLE
ROMEO run in matlab

### ISSUE THREAD

**Issue by tayebehebrahimi64** [korbinian90/ROMEO#16]
Hi,
I am trying to run romeo for phase unwrapping via Matlab. I downloaded mritools V3.6.6. But when I run example_ROMEO_call.m file according my data, it gives an error:

Error using ROMEO
ROMEO unwrapping failed! Check input files for corruption in /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/bin/romeo_tmp.

![image](https://github.com/korbinian90/ROMEO/assets/124914449/dcc35b5c-4943-47c3-b5c3-4622e2609674)

Could you please help me to fix it.

Thank you.

**Comment by korbinian90** [comment]
Hi,
This seems to be this problem: https://github.com/korbinian90/ROMEO#issues-when-calling-from-matlab
Please try if the suggested solution works and report back here ;)

Best,
Korbinian

**Comment by tayebehebrahimi64** [comment]
Hi,
Thank you very much. I realized that the version of GLIBC on my system is old. So, I downloaded mritools-linux3.5.5. then I ran the following command in terminal:
$ export LD_PRELOAD=/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/lib/julia/libstdc++.so

and then I ran the matlab code called example_ROMEO_call.m from mritools_v3.5.5 but this time after I received same error:

![image](https://github.com/korbinian90/ROMEO/assets/124914449/6f12c308-5052-4c58-ae95-cd12299a4bbd)

**Comment by tayebehebrahimi64** [comment]
Thank you for your reply. According to the solution mentioned in the link, I export LD_PRELOAD for mritools_ubuntu_v3.6.6 as well as I did the same for mritools_linux_3.5.5. And then I ran the ROMEO (I mean, according to example_ROMEO_call.m). but I received the following error for mritools_ubuntu_v3.6.6:

ROMEO command: "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/matlab/../bin/romeo" "-p" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/bin/romeo_tmp/Phase.nii" "-o" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/bin/romeo_tmp/Unwrapped.nii" "-B" "-m" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/bin/romeo_tmp/Mag.nii" "-t" "[6.61 12.85 19.09 25.33 31.57]" "-k" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/bin/romeo_tmp/Mask.nii" "--phase-offset-correction" "off" --verbose -q -i
/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/matlab/../bin/romeo: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/matlab/../bin/romeo)
Error using ROMEO
**ROMEO unwrapping failed! Check input files for corruption in /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_ubuntu/bin/romeo_tmp**


and after a long processing procedur, the following error for mritools_linux_v3.5.5:

main at /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo (unknown line)
__libc_start_main at /lib64/libc.so.6 (unknown line)
_start at /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo (unknown line)
Allocations: 3504926 (Pool: 3503489; Big: 1437); GC: 5
"/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo" "-p" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Phase.nii" "-o" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Unwrapped.nii" "-B" "-m" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mag.nii" "-t" "[6.61 12.85 19.09 25.33 31.57]" "-k" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mask.nii" "--phase-offset-correction" "off" --verbose -q -i: Illegal instruction
Error using ROMEO
**ROMEO unwrapping failed! Check input files for corruption in /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp**


Could you please do me a favor and help me fix that error?

**Comment by korbinian90** [comment]
From the last screenshot you sent, it looked like you solved the glibc problem. I'm currently on the road and will read it later in detail, but the message pointed to the input nifti having 5 echoes, but only 3 echo times were specified. Can you try to use -t [1,2,3,4,5] eg. ?

**Comment by tayebehebrahimi64** [comment]
Hi, 
I tried t=[1,2,3,4,5] but again the same error:

parameters.TE = [1,2,3,4,5];
>> [unwrapped, B0] = ROMEO(phase, parameters);
ROMEO command: "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo" "-p" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Phase.nii" "-o" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Unwrapped.nii" "-B" "-m" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mag.nii" "-t" "[1 2 3 4 5]" "-k" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mask.nii" "--phase-offset-correction" "off" --verbose -q -i
Phase loaded!
Mag loaded!
Echoes are 1:5
TEs are [1, 2, 3, 4, 5]
Trying to read mask from file /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mask.nii
individual unwrapping is true
perform unwrapping...
Invalid instruction at 0x7f20ba875f17: 0xc4, 0xe2, 0xc2, 0xf7, 0xd2, 0x48, 0x85, 0xd2, 0x75, 0xdf, 0x48, 0x89, 0x7c, 0x24, 0x38

signal (4): Illegal instruction
in expression starting at none:1
mpfr_const_pi_internal at /N/soft/rhel7/gcc/infrastructure/lib/libmpfr.so (unknown line)
.
.
.
.


checked_eval_string at /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo (unknown line)
main at /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo (unknown line)
__libc_start_main at /lib64/libc.so.6 (unknown line)
_start at /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo (unknown line)
Allocations: 3497039 (Pool: 3495600; Big: 1439); GC: 5
"/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/matlab/../bin/romeo" "-p" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Phase.nii" "-o" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Unwrapped.nii" "-B" "-m" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mag.nii" "-t" "[1 2 3 4 5]" "-k" "/N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp/Mask.nii" "--phase-offset-correction" "off" --verbose -q -i: Illegal instruction
Error using ROMEO
ROMEO unwrapping failed! Check input files for corruption in /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/mritools_Linux_3.5.5/bin/romeo_tmp

It is nice of you if you have any clue to fix this error.
Best,
Tina

**Comment by tayebehebrahimi64** [comment]
I tried to run romeo through command line. I could not run it through mritools, so I used romeo_linux_3.4.8 version. for the first time I got results, but I repeated the same procedure for another data, it does not work. I am pasting the error message:

$ **romeo -p PHASE_0004.nii -m MAG_0004.nii -k mask_0004.nii -B -t [6.62,12.85,19.09,25.33,31.57] -o /N/project/dMRI1/CARE_CSI/ANALYSIS/QSM/temp/Tina/romeo_linux_3.2.8/bin/res**
Invalid instruction at 0x7fe078d75f17: 0xc4, 0xe2, 0xc2, 0xf7, 0xd2, 0x48, 0x85, 0xd2, 0x75, 0xdf, 0x48, 0x89, 0x7c, 0x24, 0x38

signal (4): Illegal instruction
in expression starting at none:1
mpfr_const_pi_internal at /N/soft/rhel7/gcc/infrastructure/lib/libmpfr.so (unknown line)
mpfr_cache at /N/soft/rhel7/gcc/infrastructure/lib/libmpfr.so (unknown line)
#BigFloat#1 at ./irrationals.jl:177 [inlined]
BigFloat at ./irrationals.jl:176 [inlined]
BigFloat at ./irrationals.jl:176 [inlined]
#803 at ./irrationals.jl:69
setprecision at ./mpfr.jl:952
Type at ./irrationals.jl:68
unknown function (ip: 0x7fe03b08e56f)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:713
jl_f__apply_pure at /buildworker/worker/package_linux64/build/src/builtins.c:739
pure_eval_call at ./compiler/abstractinterpretation.jl:1026
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:57
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1900
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1900
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
abstract_call_method at ./compiler/abstractinterpretation.jl:504
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
abstract_call_known at ./compiler/abstractinterpretation.jl:1342
abstract_call at ./compiler/abstractinterpretation.jl:1397
abstract_call at ./compiler/abstractinterpretation.jl:1382
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
typeinf_local at ./compiler/abstractinterpretation.jl:1918
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
_typeinf at ./compiler/typeinfer.jl:226
typeinf at ./compiler/typeinfer.jl:209
typeinf_ext at ./compiler/typeinfer.jl:909
typeinf_ext_toplevel at ./compiler/typeinfer.jl:942
typeinf_ext_toplevel at ./compiler/typeinfer.jl:938
jfptr_typeinf_ext_toplevel_9901.clone_1 at /geode2/home/u100/tinabrah/Carbonate/Documents/mritools_linux_3.2.8/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
jl_type_infer at /buildworker/worker/package_linux64/build/src/gf.c:295
jl_generate_fptr at /buildworker/worker/package_linux64/build/src/jitlayers.cpp:338
jl_compile_method_internal at /buildworker/worker/package_linux64/build/src/gf.c:1980
jl_compile_method_internal at /buildworker/worker/package_linux64/build/src/gf.c:2246 [inlined]
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2239 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
unwrapping_main at /home/korbi/.julia/dev/RomeoApp/src/caller.jl:137
julia_main at /home/korbi/.julia/dev/RomeoApp/src/RomeoApp.jl:12
jfptr_julia_main_63607.clone_1 at /geode2/home/u100/tinabrah/Carbonate/Documents/mritools_linux_3.2.8/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:126
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:215
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:166 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:587
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:731
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:885
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:830
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:944
jl_eval_string at /buildworker/worker/package_linux64/build/src/jlapi.c:115
**checked_eval_string at romeo (unknown line)
main at romeo (unknown line)
__libc_start_main at /lib64/libc.so.6 (unknown line)
_start at romeo (unknown line)
Allocations: 2691021 (Pool: 2689906; Big: 1115); GC: 3
Illegal instruction (core dumped)**


sorry for this long message. I am confused about this error. Could you please help me to fix it?
Thank you

**Comment by korbinian90** [comment]
Hi,
I'm sorry that it is so troublesome for you to run ROMEO!

I have two ideas what might fail here:
1) library mismatch again, the MRI tools package should ship with it's on dependencies and use them. When used from the command line this should use the correct dependencies, so I'm not sure why it would fail here. You could try the newest version in the command line. Another solution would be to use it via Options 2, 3 or 4 (https://github.com/korbinian90/ROMEO#get-romeo).
2) Datatype, it says something about Big float, however I never explicitly used big float, but ROMEO adapts to the Datatype of the nifti. Maybe something goes wrong there. Can you try to save the nifti again in single datatype (also called float32). Alternatively, you could send me the data (email [k.eckstein@uq.edu.au](mailto:k.eckstein@uq.edu.au)). Then I would try to debug it.

Since one dataset worked, the library problem shouldn't be the issue here. So I'm more leaning towards a nifti datatype that ROMEO struggles with.

Best
Korbinian

**Comment by korbinian90** [comment]
probably related #17
