### ISSUE TITLE
romeo_linux_3.2.8.tar.gz is not gz compressed (it's a plain tar file)

### ISSUE THREAD

**Issue by stebo85** [korbinian90/ROMEO#8]
Dear @korbinian90 

[romeo_linux_3.2.8.tar.gz](https://github.com/korbinian90/ROMEO/releases/download/v3.2.8/romeo_linux_3.2.8.tar.gz)

is just a plain tar file and not gz compressed

it's probably not a problem for most users, but neurodesk's CI tripped over it :p

**Comment by korbinian90** [comment]
Thanks @stebo85 !
I compressed it and reuploaded

This is the last "manually compiled" release. From now on, the compilation will be performed automatically with github actions: https://github.com/korbinian90/CompileMRI.jl/blob/master/.github/workflows/compile.yml

The new version contains executables for romeo, clearswi and mcpc3ds and is called mritools. I just have to figure out, where I will put the compiled binaries. They are automatically added as a release on the repository CompileMRI.jl. I will probably link to that repository from korbinian90/ROMEO.

The internal structure of the compiled files stays the same, there are just the additional executables "clearswi" and "mcpc3ds"

**Comment by stebo85** [comment]
Great - thank you :)
